#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────
# AI Code Review — Self-Hosted Setup Wizard
# Hybrid mode: interactive first run, validation on subsequent runs.
# ──────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; }

# ── Helper: prompt with default ──────────────────────────
ask() {
  local prompt="$1"
  local default="${2:-}"
  local var_name="$3"
  local is_secret="${4:-false}"

  if [ -n "$default" ]; then
    prompt="$prompt [$default]"
  fi

  if [ "$is_secret" = "true" ]; then
    echo -n "$prompt: "
    read -rs value
    echo
  else
    read -rp "$prompt: " value
  fi

  value="${value:-$default}"
  eval "$var_name='$value'"
}

# ── Generate random string ──────────────────────────────
generate_secret() {
  openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p -c 64 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))"
}

# ── Interactive first-run setup ──────────────────────────
run_interactive_setup() {
  echo
  echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}   AI Code Review — Self-Hosted Setup              ${NC}"
  echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
  echo

  # Step 1: Azure DevOps connection
  info "Step 1/5: Azure DevOps Connection"
  echo "  You need a Personal Access Token (PAT) with 'Code (Read & Write)' scope."
  echo
  ask "  Azure DevOps organization name (e.g., myorg)" "" ADO_ORG
  ask "  Azure DevOps project name" "" ADO_PROJECT
  ask "  Personal Access Token (PAT)" "" ADO_PAT true
  echo

  # Step 2: LLM provider
  info "Step 2/5: LLM Provider"
  echo "  Choose your LLM provider for code review analysis."
  echo "  1) Anthropic (recommended)"
  echo "  2) OpenAI"
  echo "  3) Azure OpenAI"
  echo
  ask "  Provider (1/2/3)" "1" LLM_CHOICE

  LLM_PROVIDER=""
  LLM_API_KEY=""
  AZURE_ENDPOINT=""
  case "$LLM_CHOICE" in
    1)
      LLM_PROVIDER="anthropic"
      ask "  Anthropic API key" "" LLM_API_KEY true
      ;;
    2)
      LLM_PROVIDER="openai"
      ask "  OpenAI API key" "" LLM_API_KEY true
      ;;
    3)
      LLM_PROVIDER="azure_openai"
      ask "  Azure OpenAI endpoint" "" AZURE_ENDPOINT
      ask "  Azure OpenAI API key" "" LLM_API_KEY true
      ;;
    *)
      fail "Invalid choice. Defaulting to anthropic."
      LLM_PROVIDER="anthropic"
      ask "  Anthropic API key" "" LLM_API_KEY true
      ;;
  esac
  echo

  # Step 3: Database
  info "Step 3/5: Database"
  echo "  Use the bundled PostgreSQL or connect to an external database."
  echo
  ask "  Use bundled PostgreSQL? (y/n)" "y" USE_BUNDLED_DB

  DB_PASSWORD=""
  EXTERNAL_DB_URL=""
  if [ "$USE_BUNDLED_DB" = "y" ] || [ "$USE_BUNDLED_DB" = "Y" ]; then
    DB_PASSWORD="$(generate_secret)"
    info "  Generated database password automatically."
  else
    ask "  External DATABASE_URL" "" EXTERNAL_DB_URL
  fi
  echo

  # Step 4: Optional features
  info "Step 4/5: Optional Features"
  ask "  Enable Redis for async processing? (y/n)" "n" ENABLE_REDIS
  ask "  Enable Axon code intelligence? (y/n)" "n" ENABLE_AXON
  echo

  # Step 5: Generate .env
  info "Step 5/5: Generating configuration..."
  WEBHOOK_SECRET="$(generate_secret)"

  # Build .env file
  cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit as needed, then run: docker compose up -d

DEPLOYMENT_MODE=self-hosted

# Azure DevOps
ADO_ORG=$ADO_ORG
ADO_PROJECT=$ADO_PROJECT
ADO_PAT=$ADO_PAT
WEBHOOK_SECRET=$WEBHOOK_SECRET

# LLM Provider
LLM1_PROVIDER=$LLM_PROVIDER
LLM2_PROVIDER=$LLM_PROVIDER
ENVEOF

  case "$LLM_PROVIDER" in
    anthropic)
      echo "ANTHROPIC_API_KEY=$LLM_API_KEY" >> "$ENV_FILE"
      ;;
    openai)
      echo "OPENAI_API_KEY=$LLM_API_KEY" >> "$ENV_FILE"
      ;;
    azure_openai)
      echo "AZURE_OPENAI_ENDPOINT=$AZURE_ENDPOINT" >> "$ENV_FILE"
      echo "AZURE_OPENAI_API_KEY=$LLM_API_KEY" >> "$ENV_FILE"
      ;;
  esac

  if [ -n "$EXTERNAL_DB_URL" ]; then
    echo "DATABASE_URL=$EXTERNAL_DB_URL" >> "$ENV_FILE"
  else
    cat >> "$ENV_FILE" <<DBEOF

# Database (bundled)
POSTGRES_USER=llmreview
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=llmreview
DBEOF
  fi

  cat >> "$ENV_FILE" <<RESTEOF

# Optional features
AXON_ENABLED=${ENABLE_AXON:-false}

# Server
PORT=3000
LOG_LEVEL=info

# Limits
MAX_FILES=20
MAX_TOTAL_DIFF_LINES=2000
MAX_HUNKS=80
HUNK_CONTEXT_LINES=20
TOKEN_BUDGET_LLM1=3000
TOKEN_BUDGET_LLM2=6000
RATE_LIMIT_MAX=30
RATE_LIMIT_WINDOW_MS=60000

# LLM3 (optional accessibility checker)
LLM3_ENABLED=false
RESTEOF

  ok "Configuration written to .env"
  echo
}

# ── Level 3 Validation: presence + format + connectivity ─
validate() {
  local errors=0

  info "Validating configuration..."

  # Source the env file
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a

  # ── Presence checks ──
  if [ -z "${ADO_ORG:-}" ]; then
    fail "ADO_ORG is not set"
    errors=$((errors + 1))
  else
    ok "ADO_ORG = $ADO_ORG"
  fi

  if [ -z "${ADO_PAT:-}" ]; then
    fail "ADO_PAT is not set"
    errors=$((errors + 1))
  else
    ok "ADO_PAT is set (${#ADO_PAT} chars)"
  fi

  # LLM key check
  local has_llm_key=false
  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    ok "ANTHROPIC_API_KEY is set"
    has_llm_key=true
  fi
  if [ -n "${OPENAI_API_KEY:-}" ]; then
    ok "OPENAI_API_KEY is set"
    has_llm_key=true
  fi
  if [ -n "${AZURE_OPENAI_API_KEY:-}" ] && [ -n "${AZURE_OPENAI_ENDPOINT:-}" ]; then
    ok "Azure OpenAI is configured"
    has_llm_key=true
  fi
  if [ "$has_llm_key" = "false" ]; then
    fail "No LLM API key configured (need ANTHROPIC_API_KEY, OPENAI_API_KEY, or AZURE_OPENAI_API_KEY)"
    errors=$((errors + 1))
  fi

  # DB check
  if [ -z "${DATABASE_URL:-}" ] && [ -z "${POSTGRES_PASSWORD:-}" ]; then
    fail "No database configured (need DATABASE_URL or POSTGRES_PASSWORD)"
    errors=$((errors + 1))
  else
    ok "Database configuration present"
  fi

  # ── Connectivity checks ──
  info "Checking connectivity..."

  # PostgreSQL
  local db_url="${DATABASE_URL:-postgresql://${POSTGRES_USER:-llmreview}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-llmreview}}"
  if command -v pg_isready &>/dev/null; then
    if pg_isready -d "$db_url" -t 3 &>/dev/null; then
      ok "PostgreSQL is reachable"
    else
      warn "PostgreSQL is not reachable (may not be started yet)"
    fi
  else
    warn "pg_isready not found, skipping PostgreSQL connectivity check"
  fi

  # Azure DevOps
  local ado_url="https://dev.azure.com/${ADO_ORG}/_apis/connectionData"
  local http_code
  http_code=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: Basic $(echo -n ":${ADO_PAT}" | base64)" \
    --connect-timeout 5 \
    "$ado_url" 2>/dev/null) || true
  if [ "$http_code" = "200" ]; then
    ok "Azure DevOps connection successful (org: $ADO_ORG)"
  elif [ "$http_code" = "401" ] || [ "$http_code" = "203" ]; then
    fail "Azure DevOps authentication failed — check ADO_PAT"
    errors=$((errors + 1))
  elif [ -n "$http_code" ] && [ "$http_code" != "000" ]; then
    warn "Azure DevOps returned HTTP $http_code"
  else
    warn "Could not reach Azure DevOps (network issue?)"
  fi

  # LLM provider
  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    http_code=$(curl -s -o /dev/null -w "%{http_code}" \
      -H "x-api-key: ${ANTHROPIC_API_KEY}" \
      -H "anthropic-version: 2023-06-01" \
      --connect-timeout 5 \
      "https://api.anthropic.com/v1/messages" 2>/dev/null) || true
    # 400 = valid key, bad request (no body); 401 = invalid key
    if [ "$http_code" = "400" ] || [ "$http_code" = "200" ]; then
      ok "Anthropic API key is valid"
    elif [ "$http_code" = "401" ]; then
      fail "Anthropic API key is invalid"
      errors=$((errors + 1))
    else
      warn "Could not verify Anthropic API key (HTTP $http_code)"
    fi
  fi

  if [ -n "${OPENAI_API_KEY:-}" ]; then
    http_code=$(curl -s -o /dev/null -w "%{http_code}" \
      -H "Authorization: Bearer ${OPENAI_API_KEY}" \
      --connect-timeout 5 \
      "https://api.openai.com/v1/models" 2>/dev/null) || true
    if [ "$http_code" = "200" ]; then
      ok "OpenAI API key is valid"
    elif [ "$http_code" = "401" ]; then
      fail "OpenAI API key is invalid"
      errors=$((errors + 1))
    else
      warn "Could not verify OpenAI API key (HTTP $http_code)"
    fi
  fi

  echo
  if [ "$errors" -gt 0 ]; then
    fail "$errors validation error(s) found. Fix the issues above and re-run ./setup.sh"
    return 1
  else
    ok "All checks passed!"
    return 0
  fi
}

# ── Main ─────────────────────────────────────────────────

# Hybrid: interactive if no .env, validate if .env exists
if [ ! -f "$ENV_FILE" ]; then
  info "No .env file found. Starting interactive setup..."
  run_interactive_setup
fi

echo
validate

echo
info "To start the service:"
PROFILES=""
if grep -q "AXON_ENABLED=true" "$ENV_FILE" 2>/dev/null; then
  PROFILES="--profile axon"
fi
if grep -q "REDIS_URL" "$ENV_FILE" 2>/dev/null || grep -q "ENABLE_REDIS=y" "$ENV_FILE" 2>/dev/null; then
  PROFILES="$PROFILES --profile redis"
fi

if [ -n "$PROFILES" ]; then
  echo "  docker compose $PROFILES up -d"
else
  echo "  docker compose up -d"
fi
echo
